// app/layout.tsx
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./_components/ThemeProvider";
import Navbar from "./_components/Navbar";
import { fontVars } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen w-screen" suppressHydrationWarning>
      <body
        className={cn(
          fontVars,
          "font-sans antialiased h-full min-h-screen w-full"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid grid-rows-[auto_1fr] h-full w-full overflow-y-auto scrollbar-hide">
            <Navbar />
            <main
              className={[
                "min-h-[391px] h-full w-full overflow-y-hidden",
                "bg-white dark:bg-black",
                "[background-size:20px_20px]",
                "[background-image:radial-gradient(#d4d4d4_1px,transparent_1px)]",
                "dark:[background-image:radial-gradient(#404040_1px,transparent_1px)]",
              ].join(" ")}
            >
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
