package com.example.backend.coins;

import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table("coins")
public class Coin {

    /** Autogenerated alphanumeric string (e.g., UUID as text) */
    @Id
    private String id;

    /** CoinGecko coin id (unique, not null) */
    @Column("coin_gecko_id")
    private String coinGeckoId;

    /** Stored exactly as returned by CoinGecko */
    private String symbol;

    private String name;

    /** GitHub URLs from links.repos_url.github (Postgres text[]) */
    @Column("coin_gecko_repo_url_github")
    private String[] coinGeckoRepoUrlGithub;

    @CreatedDate
    @Column("created_at")
    private Instant createdAt;

    @LastModifiedDate
    @Column("updated_at")
    private Instant updatedAt;
}
